spring:
  application:
    name: level-up-together-mvp

server:
  port: 8443

encrypt:
  key: key-brian

app:
  dev-config-server-ip: 121.136.108.44
  dev-discovery-server-ip: 121.136.108.44
  dev-db-server-ip: 121.136.108.44

  prod-config-server-ip: 0.0.0.0
  prod-discovery-server-ip: 0.0.0.0
  prod-db-server-ip: 0.0.0.0
